{"uuid": "06e8f6d1-af65-4d8a-9e68-06c1daf2f008", "children": ["ae8a559e-daa3-44e4-b1a5-3f3c7cd1547b"], "befores": [{"name": "set_up", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=109.0.5414.120)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00A46643]\n\t(No symbol) [0x009DBE21]\n\t(No symbol) [0x008DDA9D]\n\t(No symbol) [0x008BEF6A]\n\t(No symbol) [0x00933AAB]\n\t(No symbol) [0x009461B6]\n\t(No symbol) [0x0092FB76]\n\t(No symbol) [0x009049C1]\n\t(No symbol) [0x00905E5D]\n\tGetHandleVerifier [0x00CBA142+2497106]\n\tGetHandleVerifier [0x00CE85D3+2686691]\n\tGetHandleVerifier [0x00CEBB9C+2700460]\n\tGetHandleVerifier [0x00AF3B10+635936]\n\t(No symbol) [0x009E4A1F]\n\t(No symbol) [0x009EA418]\n\t(No symbol) [0x009EA505]\n\t(No symbol) [0x009F508B]\n\tBaseThreadInitThunk [0x76BB00F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77387BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77387B8E+238]\n\n", "trace": "  File \"C:\\Users\\Henok\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Henok\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Henok\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Henok\\Desktop\\Demoblaze_Selenium_Project\\Web\\Base\\base.py\", line 18, in set_up\n    self.driver.maximize_window()\n  File \"C:\\Users\\Henok\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 592, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Henok\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Henok\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1675668645403, "stop": 1675668650055}], "start": 1675668645403, "stop": 1675668650246}