{"name": "test_login_with_incorrectly_UserName_and_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 404\n +  where 200 = <Response [200]>.status_code", "trace": "self = <API.Tests.test_login.Test_Login object at 0x0000021EA99CAE50>\n\n    @allure.description('Login when UserName & password incorrectly')\n    def test_login_with_incorrectly_UserName_and_password(self):\n        url = Login_Locators.url_login\n        data = Login_Locators.Invalid_password_and_UserName\n        Req = requests.post(url, json=data)\n>       assert Req.status_code == 404\nE       assert 200 == 404\nE        +  where 200 = <Response [200]>.status_code\n\ntest_login.py:38: AssertionError"}, "description": "Login when UserName & password incorrectly", "start": 1675622979930, "stop": 1675622980317, "uuid": "7f641cd1-4c24-4fb2-9b6a-1047592650e1", "historyId": "e9168705ee4fb0eb9eef5743bb6d9966", "testCaseId": "63e89a6bd555e71c565ba7203044dc8a", "fullName": "test_login.Test_Login#test_login_with_incorrectly_UserName_and_password", "labels": [{"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "DESKTOP-4H4LEB1"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}