{"name": "test_SignUp_with_incorrectly_UserName_and_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 404\n +  where 200 = <Response [200]>.status_code", "trace": "self = <API.Tests.test_SignUp.Test_SignUp object at 0x0000021EA99BFED0>\n\n    @allure.description('SignUp when UserName & password incorrectly')\n    def test_SignUp_with_incorrectly_UserName_and_password(self):\n        url = Login_Locators.url_login\n        data = Login_Locators.Invalid_password_and_UserName\n        Req = requests.post(url, json=data)\n>       assert Req.status_code == 404\nE       assert 200 == 404\nE        +  where 200 = <Response [200]>.status_code\n\ntest_SignUp.py:38: AssertionError"}, "description": "SignUp when UserName & password incorrectly", "start": 1675622977901, "stop": 1675622978304, "uuid": "13f6db29-72e4-4823-a48b-521891f6b4b1", "historyId": "6d8a59c16bd305ecf1d246dfc2d92a7d", "testCaseId": "e6a6a1f5ddcffb52499f09b2e8b6d606", "fullName": "test_SignUp.Test_SignUp#test_SignUp_with_incorrectly_UserName_and_password", "labels": [{"name": "suite", "value": "test_SignUp"}, {"name": "subSuite", "value": "Test_SignUp"}, {"name": "host", "value": "DESKTOP-4H4LEB1"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_SignUp"}]}