{"name": "test_SignUp_with_incorrectly_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 404\n +  where 200 = <Response [200]>.status_code", "trace": "self = <API.Tests.test_SignUp.Test_SignUp object at 0x0000021EA99BF1D0>\n\n    @allure.description('SignUp when password incorrectly')\n    def test_SignUp_with_incorrectly_password(self):\n        url = Login_Locators.url_login\n        data = Login_Locators.Invalid_password\n        Req = requests.post(url, json=data)\n>       assert Req.status_code == 404\nE       assert 200 == 404\nE        +  where 200 = <Response [200]>.status_code\n\ntest_SignUp.py:22: AssertionError"}, "description": "SignUp when password incorrectly", "start": 1675622976996, "stop": 1675622977429, "uuid": "80856796-5e11-4b02-9ab1-bd2ba86a13ec", "historyId": "f1ebd86fb3c8e4726175a3446771f32e", "testCaseId": "ab7ac4d5372315647717d526f317caa9", "fullName": "test_SignUp.Test_SignUp#test_SignUp_with_incorrectly_password", "labels": [{"name": "suite", "value": "test_SignUp"}, {"name": "subSuite", "value": "Test_SignUp"}, {"name": "host", "value": "DESKTOP-4H4LEB1"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_SignUp"}]}