{"name": "test_SignUp_with_incorrectly_UserName", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 404\n +  where 200 = <Response [200]>.status_code", "trace": "self = <API.Tests.test_SignUp.Test_SignUp object at 0x0000021EA99BF810>\n\n    @allure.description('SignUp when UserName incorrectly')\n    def test_SignUp_with_incorrectly_UserName(self):\n        url = Login_Locators.url_login\n        data = Login_Locators.Invalid_UserName\n        Req = requests.post(url, json=data)\n>       assert Req.status_code == 404\nE       assert 200 == 404\nE        +  where 200 = <Response [200]>.status_code\n\ntest_SignUp.py:30: AssertionError"}, "description": "SignUp when UserName incorrectly", "start": 1675622977498, "stop": 1675622977885, "uuid": "b8edf78c-364e-46d2-a425-d0e83bd34683", "historyId": "91a96bbdaac38394dff7233e290d6306", "testCaseId": "edcc8646b7aa54f530a5c3fea5758a45", "fullName": "test_SignUp.Test_SignUp#test_SignUp_with_incorrectly_UserName", "labels": [{"name": "suite", "value": "test_SignUp"}, {"name": "subSuite", "value": "Test_SignUp"}, {"name": "host", "value": "DESKTOP-4H4LEB1"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_SignUp"}]}